### ISSUE TITLE
method_result has problems decoding list of games

### ISSUE THREAD

**Issue by ondrowan** [Lagg/steamodd#35]
I tried to fetch list of my games from Steam library:

```python
games = api.interface('IPlayerService').GetOwnedGames(steamid=76561198017493014, include_appinfo=1)
print(games['response']['games'])
```
and got:
> UnicodeEncodeError: 'ascii' codec can't encode character '\xae' in position 16239: ordinal not in range(128)

[`data.decode`](https://github.com/Lagg/steamodd/blob/master/steam/api.py#L238) seems to have problems with trademarks in names of Warhammer titles.

I'm using Python 3.3.

---

I imagine it's easy to fix, but wouldn't it make more sense to use `requests` (which returns body as unicode strings) instead of `urllib`? It is easier to use, it'd simplify `http_downloader` and you wouldn't have to deal with those obscure errors.

**Comment by Lagg** [comment]
Oh how I would like to not worry about unicode errors anymore. But since I'm trying really hard to keep away from third party dependencies it limits me a bit. Can  you give me the app ID of the particular Warhammer game in question? I'll write a fix and use the string for a new testcase.

**Comment by ondrowan** [comment]
`15620`, `20570`, `56400` are Dawn of War 2 games from my library which contain `®` and `™` characters.

**Comment by Lagg** [comment]
Okay, will make a fix and patch release in a bit. Thanks for report.

**Comment by Lagg** [comment]
Hrm, I just did a test on both 3.4.2 and 2.7.9 and didn't get this exception. Are you using steamodd 4.18?

**Comment by ondrowan** [comment]
It was a false positive of course -_- I was printing output of given call to console and Python 3, for some reason, refused to print utf-8 characters. I had to set `PYTHONIOENCODING=utf-8`. I'm still not sure why it's an issue, I thought Python 3 did this automatically.

Sorry for your wasted time, I'll write a patch or two later on as a compensation.

**Comment by Lagg** [comment]
Phew, no problem. I'm just happy that I didn't have to fix yet more unicode stuff, and yeah I thought python 3 did that automatically too. I remember the release notes specifically saying they normalized *everything* to utf-8 including the site.py encoding line and repl. Hopefully what happened on your install is just a fluke because having some part of 3 still assuming ascii by default is the last thing we need when the migration is tricky enough as it is.
