### ISSUE TITLE
Add support for steam store API

### ISSUE THREAD

**Issue by mithron** [Lagg/steamodd#44]
Hello. 
It seems to me that adding steam store API support is useful. The API is described here: https://wiki.teamfortress.com/wiki/User:RJackson/StorefrontAPI#Known_methods 

For example, it can deliver game info by appid .

**Comment by miedzinski** [comment]
If anyone wants to implement something, here is list of all available interfaces and methods:
http://api.steampowered.com/ISteamWebAPIUtil/GetSupportedAPIList/v0001/
You can view more interfaces by providing API key (append ?key= to URL).

**Comment by Lagg** [comment]
Ah man I missed multiple issues posted around this timeframe. I never got any GH alert or mail for them. I'm not sure what I did wrong and apologize to posters. D:
