### ISSUE TITLE
Ability to manage steam groups?

### ISSUE THREAD

**Issue by psbj** [Lagg/steamodd#46]
I apologize for my ignorance, but would it be possible to add the ability to manage steam groups?

Specifically, I'd like a way to post an announcement with this library.

**Comment by Lagg** [comment]
No, at the moment it's more or less just for the "formal" APIs exposed and special scraping cases like for steam.sim. I don't think such a thing exists for group announcements and you have to request the steamcommunity.com pages yourself. One cool project to look at if you don't mind node is https://github.com/DoctorMcKay/node-steamcommunity/wiki/CSteamGroup - it should satisfy your requirements.
