### ISSUE TITLE
How to accept/decline steam trade offer with it api?

### ISSUE THREAD

**Issue by ThreadShakur** [Lagg/steamodd#47]
How anybody give me example?

**Comment by Lagg** [comment]
The API doesn't support the prerequisites for trading, like logins and actually creating/sending the offer. What trading involves is basically the same pages your browser visits. For this reason steamodd doesn't and probably won't support such things. Neither will the other 2 libs you opened an issue for I'm guessing. What you want is something like @DoctorMcKay's node libs like `steam-tradeoffer-manager` and `steam-user`. Which support the login flow and all relevant Steam requests and protobufs. Or perhaps SteamRE if node.js isn't your preferred thing. SteamRE also has python bindings if I recall correctly.


https://bitbucket.org/AzuiSleet/pysteamkit
