### ISSUE TITLE
Conflicts with modual of the same name

### ISSUE THREAD

**Issue by Zwork101** [Lagg/steamodd#48]
I have already installed steam, another python library for steam, and when installing this for trading, python will over ride steamodd and import steam. How can I use both?

Btw, if the answer is 'virtual environment' then can you explain the steps? I've never used one before.

**Comment by Lagg** [comment]
Never even saw this issue for some reason, and I'm guessing that any advice I can give about package aliasing is as outdated as this issue. Sorry D:
