### ISSUE TITLE
How does this manage to get user's private info?

### ISSUE THREAD

**Issue by addrum** [Lagg/steamodd#49]
According to the steam web api docs, `GetPlayerSummaries` has some private info (`gameextrainfo` is what I'm most interested in) which seems to only be accessible through implementing openid which this library doesn't seem to do. Could you explain how this works?

**Comment by Lagg** [comment]
I don't know if openid would help in this case.  Its purpose is to prove that a given ID belongs to the entity trying to log in (i.e. If I logged onto your site, openid would tell you `76561198014028523` definitely is my account and you'll know its safe to associate me with it). You might be thinking of the OAuth. But I believe that's deprecated.

Bottom line is that Steam generally respects what the user wants for their profile perms and there aren't many ways around that besides connecting the client and getting the session cookies. Such that you can get access from them setting it to "Friends Only".

This module is mostly meant for the formally established APIs. Which are *supposed to* only require the API key.

Sorry for late response btw

**Comment by addrum** [comment]
@Lagg it's possibly the OAuth. To give you context to what I was attemtpting to do (I've since found what I was trying has already been done by someone else so this is for my own curiosity!), I went to the following url `http://api.steampowered.com/ISteamUser/GetPlayerSummaries/v2/?key=api_key_here&steamids=steam_id_here` and it would return a response, but it doesn't contain any of the private info (in my case I was looking for `gameextrainfo`), my profile is public too.

No problem for the late response! It's nothing pressing. I'll leave it open for now as I'm still a little confused so if you have any further info that'd be great!

**Comment by Lagg** [comment]
It'll only have content if the user is in a game when the request is made. Tested it on a friend that was in SFM and it appears to have set `gameid` and `gameextrainfo` correctly (`1840` and `Source Filmmaker` respectively). There's also fields for server address if applicable. Not sure if Steam could be doing something perms based with your profile. I would check every option to "public" then try again.
