### ISSUE TITLE
Transferring inventory assets

### ISSUE THREAD

**Issue by alexksso** [Lagg/steamodd#50]
Hi,

I can't find a way to transfer inventory assets & games - am I missing something?

**Comment by Lagg** [comment]
You're probably looking for trade offers, which do have decline/cancel calls in the steam API but nothing to actually send the offer or check confirmations besides the semi-formal API that Authenticator and the trade window pulls from. This module just gives some light wrappers around a core that does requests to api.steampowered.com. No custom login logic or anything of that nature.
