### ISSUE TITLE
how can I get supported languages?

### ISSUE THREAD

**Issue by csselo** [Lagg/steamodd#54]
hi

https://partner.steamgames.com/doc/store/localization#supported_languages

I want to know with api

**Comment by Lagg** [comment]
Sorry for late response, looks like github doesn't send me emails anymore. You can pass a supported language code by using the "language" param with  your requests.

e.g. `steam.api.interface('IPlayerService').GetOwnedGames(steamid=76561198014028523, include_appinfo=1, language="fr")
` if I wanted my games list in french
